# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39216005b8e233e9c556d89bb7a73c6d"
name = "easy-tick-bw"
application_url = "https://easy-tick-bw.vercel.app"
embedded = true
handle = "easy-tick-bw"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://easy-tick-bw.vercel.app/auth/callback", "https://easy-tick-bw.vercel.app/auth/shopify/callback", "https://easy-tick-bw.vercel.app/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
prefix = "apps"
subpath = "easy-tick"
url = "https://easy-tick-bw.vercel.app/proxy"

